module: add hpc_cluster_id, add default value for subscription; examp…
alibabacloud-automation/terraform-alicloud-ecs-instance pull request #58
Opened 2024-01-25 07:13 UTC by shanye997

…le: improve the examples

2024-01-26 03:32 UTC, xiaozhu36 requested changes

2024-01-26 03:32 UTC, xiaozhu36 commented on tfversion.md
> +
增加这个文件的目的是啥

2024-01-26 03:34 UTC, shanye997 commented on tfversion.md
> +
本地测试的时候生成的，我给他删掉

2024-04-07 07:53 UTC, xiaozhu36 requested changes

2024-04-07 07:53 UTC, xiaozhu36 commented on main.tf
> +  ipv6_addresses              = var.ipv6_addresses
ipv6_address_count  和 ipv6_addresses  是相互冲突的，对于相互冲突的，module 层面应该把这种问题规避掉，并且要在 module 的参数描述中说清楚，最好针对相互冲突的，单独建立example

2024-04-07 08:48 UTC, shanye997 commented on main.tf
> +  ipv6_addresses              = var.ipv6_addresses
已在 module 中增加以下判断，在指定了 ipv6_addresses 时优先取这个参数。参数描述和 example 均已添加
```
ipv6_addresses                  = var.ipv6_addresses
ipv6_address_count          = length(var.ipv6_addresses) > 0 ? null : var.ipv6_address_count
```

2024-04-08 01:55 UTC, xiaozhu36 requested changes

2024-04-08 01:55 UTC, xiaozhu36 commented on main.tf
> +  ipv6_addresses              = var.ipv6_addresses
其他的参数也一样

2024-04-08 01:55 UTC, xiaozhu36 commented on variables.tf
> +variable "is_outdated" {
这个参数不需要在module 中暴露，不需要设置，后续这个参数是要下掉的

2024-04-08 05:38 UTC, shanye997 commented on variables.tf
> +variable "is_outdated" {
已更新，增加了 secondary_private_ips、secondary_private_ip_address_count 的判断

2024-05-07 09:10 UTC, xiaozhu36 approved these changes

2024-05-07 09:28 UTC, merged